### ISSUE TITLE
Bug: TypeError: allureJsCommons.AllureConfig is not a constructor

### ISSUE THREAD

**Issue by vinceis1337** [isaaceindhoven/testcafe-reporter-allure#102]
**Describe the bug**
testcafe-reporter-allure is resolving allure-js-commons to version `2.0.0.beta-11` which was released 12 days ago. This causes an error on run that says `TypeError: allureJsCommons.AllureConfig is not a constructor`. The underlying cause is the dist/index.js file no longer has the lines

```
var AllureConfig_1 = require("./src/AllureConfig");
Object.defineProperty(exports, "AllureConfig", { enumerable: true, get: function () { return AllureConfig_1.AllureConfig; } });
```

**To Reproduce**
npm install any project with a dependency on testcafe-reporter-allure
make sure it resolves allure-js-commons to 2.0.0.beta-11 (not 2.0.0.beta-9)
attempt to run testcafe using this framework
get error

**Expected behavior**
using this framework should not result in an error

**Comment by vinceis1337** [comment]
it could be argued that this is a semantic versioning issue in allure-js-commons. I will crosslink this issue in an issue opened on their side.

**Comment by lpelypenko** [comment]
@vinceis1337 would you recommend to downgrade to 2.0.0.beta-9?
