### ISSUE TITLE
Feature: Video attachment to report

### ISSUE THREAD

**Issue by sweco-nlnofk** [isaaceindhoven/testcafe-reporter-allure#143]
**Is your feature request related to a problem? Please describe.**
Hello, we are looking for a well-maintained testcafe allure reporter to replace our old one. Our old one contains video attachment, but since its dependencies were not updated frequently we ran into some issues. 

**Describe the solution you'd like**
Since this package looks nice and well-maintained (I also hope for the long term), we would like to a have video attachment feature to the allure report. This replacement step must be done rather fast, so I was hoping, if you would consider this feature, how long would it take to implement? Then we can evaluate whether to wait for implementation or contribute ourselves. Let me know your answer as soon as you can. Thanks!

**Describe alternatives you've considered**
Copying the code and making it a local package and edit it. But this is not a sustainable solution for us.

**Additional context**
![temp](https://user-images.githubusercontent.com/79645975/144420940-a03589df-0f34-4b32-8854-21891415b0dd.PNG)

**Comment by vanhoofmaarten** [comment]
We are very much open for contributions, if you're up for it. We are glad to help you with any questions or code reviews along the way. I believe a good start to try and implement this feature is in `src/reporter/allure-reporter.ts` and take a look at how screenshots are handled. At first glance, a similar approach seems pretty straight forward.

**Comment by JazzminnNo** [comment]
Hi @vanhoofmaarten, it's me @sweco-nlnofk. I wanted to let you know that I have changed jobs recently and could not continue the pull request. Besides, no one from my previous company is going to pick this up in the near future. So if there are no other volunteers for this feature then it might be better to close this issue for now. I might be able to contribute myself in the future, but for now I am too busy with the new job.

**Comment by mrtnvh** [comment]
Thank you for sharing this, @JazzminnNo . Congratulations on your new job. 

We ourselves currently see no demand for this feature and therefore will not be continuing on this issue. I will therefore close this (for now).

For new readers: If you stumble on this issue searching for video attachment functionality and want to include this: Drop a comment or a PR, and I'll be sure to help you along.
