### ISSUE TITLE
Bug: Update Allure-commandline to fix Log4j Vuln?

### ISSUE THREAD

**Issue by Cameron-W-A** [isaaceindhoven/testcafe-reporter-allure#146]
I believe " "allure-commandline": "2.13.8"," is using a vulnerable version of Java that includes the Log4j vuln that everyone is talking about.

Is there plans to update and fix this vuln? My SCA Scanner is saying this lib is including the vulnerable jar.

**Comment by vanhoofmaarten** [comment]
Hi @Cameron-W-A,

Thank you for pointing this out. We will follow up as soon as `allure-commandline` has a new version available.

See: https://github.com/allure-framework/allure-npm/pull/34

To be clear, the `allure-commandline` is a `devDependency` in this package and only used to create and process allure reports for local development and testing. Having this package as a dependency in your project will not install this version of `allure-commandline` on your machine.

**Comment by Cameron-W-A** [comment]
@vanhoofmaarten  Looks like that MR is now merged and closed
